@startuml

!theme cerulean-outline

start
floating note left: OIDC HTTP request

partition Browser Flow {
  fork
      ->Alternative;
      partition Step : Cookie {
        if (KEYCLOAK_IDENTITY\n& User session ) then (valid)
          :SSO authenticated;
        else (next)
          stop
        endif
      }
  fork again
      ->Disabled;
      partition Step : Kerberos {
        if (SPNEGO exchange) then (Success)
          :Kerberos authenticated;
        else (next)
          stop
        endif
      }
  fork again
      ->Alternative;
      partition Step : Idp Redirector {
        if (kc_idp_hint ?) then (yes)
          :Idp Redirector;
          end
        else (next)
          stop
        endif
      }
  fork again
      ->Alternative\n\n\n;
      partition SubFlow : Form {
        partition Step : Username Password Form {
          repeat :Display login Form to user;
          ->submit credentials;
          backward:Error message;
          repeat while (Username + Password Valid ?)
        }
        partition SubFlow : Browser - Conditional OTP config {
          if (OTP configured for user) then (yes)
            partition Step : OTP Form {
              repeat :Display OTP Form to user;
                ->submit otp code;
                backward:Error message;
              repeat while (OTP Valid ?)
            }
          endif
        }
        :Authenticated;
      }

  end fork {or}
}
@enduml
