@startuml

!theme cerulean-outline

hide footbox

Actor User order 1
Participant "Navigateur" as Browser order 10
Participant "Application" as App order 20
Participant "Royaume Keycloak" as Keycloak order 30

User -> Browser
Browser -> App

App -> Browser: redirection
Browser -> Keycloak

Alt Browser Flow
    Keycloak <-> User
end

Alt Required Actions
    Keycloak <-> User
end

Keycloak <-?: Session
activate Keycloak #LightBlue

Alt Consents
    Keycloak <-> User
end

Alt Scopes
    Keycloak <-> App
end

Alt Autorisations
    App <-> User
end

@enduml
