@startuml

!theme cerulean-outline

hide footbox

title Authentification + User federations

Participant "Utilisateur" as EndUser
Participant "Navigateur" as Browser
Participant "Application" as RelyingParty
Participant "Keycloak" as OpenIdProvider
Participant "LDAP" as ldap1

EndUser -> Browser: Accède au site
Browser -> RelyingParty : Charge la page

RelyingParty -> RelyingParty : Utilisateur non authentifié
RelyingParty -> Browser: Redirection vers le serveur d'authentification

Browser -> OpenIdProvider:
OpenIdProvider -> Browser: retourne la mire d'authentification

Browser -> EndUser:

EndUser -> Browser: Envoie informations d'authentification
Browser -> OpenIdProvider:

OpenIdProvider -> OpenIdProvider: Cherche l'utilisateur dans le royaume

OpenIdProvider -> ldap1 : LDAP Bind avec username+password
ldap1 -> OpenIdProvider: OK
OpenIdProvider -> ldap1 : LDAP Search pour les LDAP_MAPPERS\n(attributs & groupes)
ldap1 -> OpenIdProvider:


OpenIdProvider -> Browser: Redirection vers l'application

Browser -> RelyingParty :

... etc ...
@enduml
