@startuml

!theme cerulean-outline

hide footbox

title Authentication Samlv2

Participant "Utilisateur" as EndUser
Participant "Navigateur" as Browser
Participant "Fournisseur de service" as ServiceProvider
Participant "Fournisseur d'identité" as IdentityProvider


group #F0F0F0 Not SAML
    EndUser -> Browser: 
    Browser -> ServiceProvider: 
    ServiceProvider->ServiceProvider: Utilisateur non authentifié
end group

ServiceProvider -> ServiceProvider: Génération d'une demande Saml
ServiceProvider -> Browser: Redirection vers le fournisseur d'identité
Browser -> IdentityProvider:

group #F0F0F0 Not SAML
    EndUser <-> IdentityProvider: Justifie de son identité
end group

IdentityProvider -> Browser: Retourne la réponse Saml encodée

Browser -> ServiceProvider:

group #F0F0F0 Not SAML
    ServiceProvider -> Browser:
    Browser -> EndUser:
end group
@enduml
